# Generated by Django 5.0.8 on 2024-08-12 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_parent_a', models.IntegerField()),
                ('number_parent_b', models.IntegerField()),
                ('result_parent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_child_a', models.IntegerField()),
                ('number_child_b', models.IntegerField()),
                ('result_child', models.IntegerField()),
                ('result_child_parent', models.IntegerField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiNinja.parent')),
            ],
        ),
    ]
